# ===========================================
#   Minimal Vercel P10k — Terminal Synced
#   Uses your iTerm Theme Sync colors
# ===========================================

POWERLEVEL9K_MODE='compat'  # no icons

# --------------------------
# Prompt Layout
# --------------------------
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  vcs
)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  time
)

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false

# --------------------------
# Directory
# --------------------------
POWERLEVEL9K_DIR_FOREGROUND=white
POWERLEVEL9K_DIR_BACKGROUND=bright-black
POWERLEVEL9K_DIR_SHORTEN_STRATEGY=truncate_to_last
POWERLEVEL9K_DIR_MAX_LENGTH=50

# --------------------------
# Git
# --------------------------
POWERLEVEL9K_VCS_BACKGROUND=black
POWERLEVEL9K_VCS_BRANCH_FOREGROUND=bright-black
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=bright-black
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=red
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=bright-black
POWERLEVEL9K_VCS_STAGED_FOREGROUND=bright-black
POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
POWERLEVEL9K_VCS_SHOW_COMMITS_AHEAD=true
POWERLEVEL9K_VCS_SHOW_COMMITS_BEHIND=true
POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND=bright-black
POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND=bright-black
POWERLEVEL9K_VCS_REMOTE=true
POWERLEVEL9K_VCS_REMOTE_FOREGROUND=bright-black

# --------------------------
# Status
# --------------------------
POWERLEVEL9K_STATUS_OK_FOREGROUND=bright-black
POWERLEVEL9K_STATUS_OK_BACKGROUND=black
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=red
POWERLEVEL9K_STATUS_ERROR_BACKGROUND=black

# --------------------------
# Time
# --------------------------
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
POWERLEVEL9K_TIME_FOREGROUND=bright-black
POWERLEVEL9K_TIME_BACKGROUND=black

# --------------------------
# Minimal Separators
# --------------------------
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=' '
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='$ '
